const Des_Data = [
  {
    id: 1,
    title: "Oriando",
    image: "https://tranquil-licorice-79e76f.netlify.app/images/dest-1.jpg",
    desc: "Orlando is a city in, and the county seat of, Orange County, Florida, United States. Part of Central Florida, it is the center of the Orlando metropolitan area, which had a population of 2,509,831 in 2017, according to the U.S. Census Bureau. It is the sixth-largest metropolitan area in the Southern United States and the third-largest metropolitan area in Florida behind Miami and Tampa Bay. ",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "Orlando is one of the most-visited cities in the world primarily due to tourism, major events, and convention traffic. It is the fourth-most visited city in the U.S. after New York City, Miami, and Los Angeles with over 4.4 million visitors as of 2019.Orlando International Airport is the 13th-busiest airport in the United States and the 29th-busiest in the world.",
    paraImage_one: "https://tranquil-licorice-79e76f.netlify.app/images/singlepage/single-1.jpg",
    paraImage_two: "https://tranquil-licorice-79e76f.netlify.app/images/singlepage/single-2.jpg",
  },
  {
    id: 2,
    title: "Miami",
    image: "https://www.bing.com/th?id=OSK.HEROoFZHWKvfn7zbT7CvBL9Z0QJartiCHsgXbIBkg5zMQjg&pid=cdx&w=320&h=189&c=7",
    desc: "Located on a barrier island and connected to the mainland by a series of bridges, Miami Beach is a mix of quiet neighborhoods, lively entertainment-focused areas, and long stretches of soft-sand beaches. Art Deco Historic District This architectural style, popular in the 1930s and 40s, dominates the trendy South Beach neighborhood.",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "Vizcaya Museum and Gardens, this is a National Historic Landmark that features a main house, ten acres of formal gardens, a rockland hammock (native forest), and soon-to-be-restored historic village2. Everglades National Park1 this is one of several popular day trip destinations from Miami. It is the largest subtropical wilderness in the United States, boasts rare and endangered species, and offers a variety of outdoor activities1",
  },
  {
    id: 3,
    title: "Los Angeles",
    image: "https://www.bing.com/th?id=OSK.HEROHFzx0Yc8lfkb3koi5QTB5jgIPVY_XndqpGTNZASvcJI&pid=cdx&w=320&h=189&c=7",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "Los Angeles covers about 469 square miles and is the county seat of Los Angeles County, which is the most populous county in the United States with an estimated 9.86 million residents as of 20221. It is the third-most visited city in the U.S. with over 4.6 million visitors as of 20191.",
    desc: "Los Angeles, often referred to by its initials L.A., is the most populous city in the U.S. The city is known for its Mediterranean climate, ethnically and culturally diverse population, in addition to a sprawling metropolitan area1. The majority of the city proper lies in a basin in Southern California adjacent to the Pacific Ocean in the west and extending partly through the Santa Monica Mountains and north into the San Fernando Valley, with the city bordering the San Gabriel Valley to its east1.",
  },
  {
    id: 4,
    title: "San Diego",
    paraImage_one: "https://tranquil-licorice-79e76f.netlify.app/images/dest-4.jpg",
    image: "https://www.bing.com/th?id=OSK.HEROx6fHHhbKLHhSHT0-79FPKjqNbsAFaMFCzT_zWbAApd0&pid=cdx&w=320&h=189&c=7",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "San Diego is also home to cutting-edge businesses in life sciences, genomics, biotechnology, telecommunications, Smart City technology, software, electronics and other major innovative industries. The city has been rated as one of the top life science and biosciences locations, and one of the most inventive cities in the world. With more than 100 languages spoken by San Diego residents who have come from all parts of the world to live here, the city truly embodies a diverse and vibrant culture.",
    desc: "San Diego is known as the birthplace of California because it was the first site visited by Europeans on the West Coast and the first permanent Spanish settlement in the state. It was historically home to the Kumeyaay people, whose culture is preserved in some areas like Old Town. The city is also a hub for innovation and tourism, with world-famous attractions and cutting-edge businesses in various fields.",
  },
  {
    id: 5,
    title: "Houston",
    image: "https://www.bing.com/th?id=OSK.HERONhZRUDps129SJP5w9V-dQE9G5GSRKHfAgXOiWTS0L3g&pid=cdx&w=320&h=189&c=7",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "The city is the seat and largest city of Harris County and the principal city of the Greater Houston metropolitan area, which is the fifth-most populous metropolitan statistical area in the United States and the second-most populous in Texas after Dallas–Fort Worth. Houston is the southeast anchor of the greater megaregion known as the Texas Triangle.",
    desc: "Houston, often referred to as ‘Space City’, is a large and diverse city located in the southeast of Texas, near the Gulf of Mexico1. It was founded in 1836 by two brothers on land near Buffalo Bayou, and named after Sam Houston, the first president of the Republic of Texas. With an estimated population of 2.5 million people, it is the fourth most populous city in the nation, and the largest in the southern U.S. and Texas. Houston is home to NASA’s Lyndon B. Johnson Space Center, which earned it the nickname 'Space City’1. It is also known as ‘The Bayou City’ because of the many bayous that run through it1. The city has a warm and humid climate, with hot and sticky summers1. Its residents speak 145 different languages, and its metropolitan area covers 9,444 square miles, larger than the state of New Jersey.",
  },
  {
    id: 6,
    title: "New York",
    image: "https://www.bing.com/th?id=OSK.HEROtttPHr_7Cinj7OYohpuOvYrrtsDRBmaaFuGvBKHFEJA&pid=cdx&w=320&h=189&c=7",
    contact_para: "Our dedicated team is here to assist you with seamless booking, travel planning, providing detailed accommodation information, handling special requests, arranging transportation, and offering constant customer support to ensure a smooth and enjoyable stay at our hotel.",
    img_info: "Our team is dedicated to making your stay and overall travel experience as comfortable as possible ",
    sidepara: "New York City, often referred to as NYC, is the most populous city in the United States1. With a population of approximately 8.3 million distributed over 300.46 square miles as of 20221, it is the most densely populated major city in the United States1. The city is located at the southern tip of New York State and is situated on one of the world’s largest natural harbors1.",
    desc: "New York City is a global city and a cultural, financial, high-tech, entertainment, and media center with a significant influence on commerce, health care, scientific output, life sciences, research, technology, education, politics, tourism, dining, art, fashion, and sports1. It is home to the headquarters of the United Nations, making it an important center for international diplomacy1.The city is also known as “the Big Apple” and the City That Never Sleeps. It has the most skyscrapers in the U.S., with 274 buildings over 492 ft. (150 m) tall1. It is the most linguistically diverse city in the world, with over 800 languages spoken and four in ten households speaking a language other than English1.",
  },
]

export default Des_Data;